# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: invoxmedics
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: vocali
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs22.x

functions:
  transcribeAudioFile:
    handler: handlers/transcribeAudioFile.transcribeAudioFile
    events:
      - httpApi:
          path: /
          method: post
  transcribeAudioInRealtime:
    handler: handlers/transcribeAudioInRealtime.transcribeAudioInRealtime
    events:
      - httpApi:
          path: /realtime
          method: post
